apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: k8s-learning
  labels:
    app: web
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        component: frontend
    spec:
      containers:
      - name: web
        image: k8s-learning/web:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: k8s-learning
  labels:
    app: web
    component: frontend
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP