apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: k8s-learning
  labels:
    app: k8s-learning
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  REDIS_PASSWORD: ""