apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: k8s-learning
  labels:
    app: worker
    component: processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        component: processor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: worker
        image: k8s-learning/worker:latest
        imagePullPolicy: Never
        ports:
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: WORKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: METRICS_PORT
          value: "9090"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        volumeMounts:
        - name: uploads-storage
          mountPath: /app/uploads
          readOnly: true
        - name: results-storage
          mountPath: /app/results
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /livez
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: uploads-pvc
      - name: results-storage
        persistentVolumeClaim:
          claimName: results-pvc