apiVersion: v1
kind: Service
metadata:
  name: controller-metrics-service
  labels:
    app: controller
    component: controller
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: controller