apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    app: controller
    component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
        component: controller
    spec:
      serviceAccountName: controller
      containers:
      - name: manager
        image: k8s-learning/controller:latest
        imagePullPolicy: IfNotPresent
        args:
        - "--leader-elect"
        - "--metrics-bind-address=:8080"
        - "--health-probe-bind-address=:8081"
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis-password
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "json"
        - name: ENABLE_AUTO_SCALING
          value: "true"
        - name: RECONCILE_INTERVAL_SECONDS
          value: "30"
        - name: METRICS_COLLECTION_INTERVAL
          value: "15s"
        - name: WORKER_IMAGE
          value: "k8s-learning/worker:latest"
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault