apiVersion: v1
kind: Service
metadata:
  name: controller-metrics-service
  labels:
    app: controller
    component: controller
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  - name: health
    port: 8081
    targetPort: health
    protocol: TCP
  selector:
    app: controller