apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-learning

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: k8s-learning/api:dev
  target:
    kind: Deployment
    name: api

- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: k8s-learning/worker:dev
  target:
    kind: Deployment
    name: worker

- patch: |-
    - op: replace
      path: /data/LOG_LEVEL
      value: debug
  target:
    kind: ConfigMap
    name: app-config

commonLabels:
  environment: development