name: Docker Lint

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - 'Dockerfile*'
  pull_request:
    paths:
      - 'docker/**'
      - 'Dockerfile*'

jobs:
  hadolint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "docker/Dockerfile.*"
          recursive: true
          failure-threshold: warning
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: false

      - name: Upload SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-results.sarif
